import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/redux-provider";
import { Suspense } from "react";
import Loading from "./loading";
import { Toaster } from "sonner";

// Configure Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <Suspense fallback={<Loading />}>
          <ReduxProvider>
            {children}
            <Toaster />
          </ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
